# Generated by Django 6.0.1 on 2026-01-10 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(16),
                            django.core.validators.MaxValueValidator(150),
                        ]
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        help_text="Wzrost w centymetrach",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(280),
                        ],
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta")], max_length=1
                    ),
                ),
                (
                    "favourite_colour",
                    models.CharField(
                        choices=[
                            ("czerwony", "Red"),
                            ("zielony", "Green"),
                            ("niebieski", "Blue"),
                            ("żółty", "Yellow"),
                            ("fioletowy", "Purple"),
                        ],
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
